grafana:
    adminUser: ENC[AES256_GCM,data:zqNPVSA=,iv:R8MdsonaZA46hVGHNLOrojz+n7K41TP086OqKn4munE=,tag:c1nS8f/WOnE5XPC2s4Wrug==,type:str]
    adminPassword: ENC[AES256_GCM,data:n7eJgKOj,iv:mPys3kATH554rN4FExOW0Boy4E5hT5DmGWZefmwGL+8=,tag:UFAU/4vvrVMdE8dVHtGGfw==,type:str]
sops:
    age:
        - recipient: age1yjhhcgfpsux6tjql3x75hn49e9yyjph4q5ltx67gt6lhryurd9sqgjsam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Qm5MdWt6bE5iaVFRNnht
            ZU9ac1JJbHlwOHR1VmgyZlA0MjEraVZndkZjCjMwdDFmakU0Y1JCQjA5M1l3OVY5
            dWQ2R3NETWJVME9IbWRLL3FWdUdSS2sKLS0tIFR4QlZXeWtNUG40bmdBUGJuTllI
            SERTUjYwZXM2Zkl1ZTZVM3A3NWc5UGMKUJDaOCUKuDIWbEXwepcl+rt53+WKZsI9
            KZLublMyq+H3CX9/9Xp7HDIhQpc0SJsotx7xS1VK5bg8n4tyGGic7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T18:58:52Z"
    mac: ENC[AES256_GCM,data:817cRmxNncB6dkDkxcQGisPor15GIfgljK0+Q1TVsusWZnD2ynv6xZdSFPWzBE98hKa+Pv+Nd8/mzCfwtLyJMWz8sJ8BTO4EJIEZoInPVOPGY4JU/hrhaGoxxD/DErYJongBdbHLNqsPjwYCIgsnNjijBjMNuvaQIjfz25tgdvQ=,iv:ENXrr2HuOr6hxPVr0D4YEyQ4ILsSzLC9TRdECvMNURU=,tag:wneEngoOflOTD8OMHequ/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
