grafana:
    adminUser: ENC[AES256_GCM,data:zqNPVSA=,iv:R8MdsonaZA46hVGHNLOrojz+n7K41TP086OqKn4munE=,tag:c1nS8f/WOnE5XPC2s4Wrug==,type:str]
    adminPassword: ENC[AES256_GCM,data:9ZP5M4W7,iv:qDaHsXotqOh65IJYdqcxxvcWTw/IGo5TToq+2dxwTmU=,tag:HUsV8VhiUGJ0QJiyQrIR0Q==,type:str]
sops:
    age:
        - recipient: age1yjhhcgfpsux6tjql3x75hn49e9yyjph4q5ltx67gt6lhryurd9sqgjsam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Qm5MdWt6bE5iaVFRNnht
            ZU9ac1JJbHlwOHR1VmgyZlA0MjEraVZndkZjCjMwdDFmakU0Y1JCQjA5M1l3OVY5
            dWQ2R3NETWJVME9IbWRLL3FWdUdSS2sKLS0tIFR4QlZXeWtNUG40bmdBUGJuTllI
            SERTUjYwZXM2Zkl1ZTZVM3A3NWc5UGMKUJDaOCUKuDIWbEXwepcl+rt53+WKZsI9
            KZLublMyq+H3CX9/9Xp7HDIhQpc0SJsotx7xS1VK5bg8n4tyGGic7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T18:01:03Z"
    mac: ENC[AES256_GCM,data:qcNgYBmoQh+LEZOfFtvEUIY0VYW3nJAsYBXxaOHLNPjMlUwmsmizsmCudZVhry452Spto3HdHxjItxvIt6z33NBqJ2tLoD8PWMINZYmCnqhUN6rg+i/ybOmqOHdGBdjTXZHzDRJ9wsqzELEdO3TvEg2ssI+lri/Chal2hVxN7iI=,iv:I7cHd1KmtY/xDxYc7pB8Uzrvt/wXag5R6Rxyx8Gc2QM=,tag:/vPZOmPJCEmPFPZjpwVnuQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
