apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-backup-pvc
  namespace: palworld
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph-filesystem
