clusters:
  - &staging age1yjhhcgfpsux6tjql3x75hn49e9yyjph4q5ltx67gt6lhryurd9sqgjsam2
  - &prod age199lgwasr5kstnswjdp7a48l34n2xjgn2zvxcy6gsfng90c9y3caszh6lq0
creation_rules:
  # static staging secrets
  - path_regex: staging.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: *staging

  # generated staging secrets
  - path_regex: staging.*\.encrypted$
    age: *staging

  - path_regex: production.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: *prod
