apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomizations/core/prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
