apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jobs
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomizations/jobs/prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: apps
