apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reloader
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: 2.2.x
      sourceRef:
        kind: HelmRepository
        name: reloader
      interval: 24h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
