---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgBS8L9fDzxTv3if3ofhVeX0ONN2CBKD+2Cj9z8v/P4xzglxd4AWw20JTMUQZTZRs5bK88cz7wRk0qo3Nvz8iJOZtiUZj4SFnlBeHo3hogCS1rTSnyJg+LwhJhEMP8WHTs7ZCpv7d8DXiISYnSfx6b/dAj4Gk50nak3Fm8819t/g2FtCwq1BbzgZ1AfvwTqb/DD+VvHIRp6u5vGys/G7+gP9oJIx0wskhRHBNC7f9siL89OW98MyzncNPSb19BKOuvlxX5LP/2oo4t07v1i3w0cv+Awc2b36Dt3y/79krn6+3zRkiz+GNfWWw5QGslFqkW3CVTx/4gB+UcS+IfK+jnZGuZ2HsqQFktt0YJUn8hyocyP36g2jKK4r/uK/di/3ljIFnFItwTXTU/XFA0PA+Q7Ud2N3hIcwMGbxXPUcCGOMhr2uEWTyBXW3cNtArF/3w5xDnm9gPbm7OufNMkgHA8G3uRpP2rodouVaWRmrVsRHm0s71+xXRVIERnS6ZlytdNl4SWY/3CP6I6TXfioHCPVaTTJeEDpCZcmmOXDXpaqUtlXVIHALvSbwFAKo/0r5LjLp+2PTn6facq0SOaHgm5HlMxqEHNwfA8DDvrhgT/6dJvEi1P6oYNdfOebkHSq4BkY4wp/b98ixAuvxU8rFR16onZ9LTv4VNtYh6L8UJgPzyUQ4shdfnuwPc1e8h73MXvZUzSjs7BhgaHCXRG6XXodH9a1qJNI2MqzIOiU4EtH48moBEM0et7bdNIzouQElRxMXz2Undzl9dy9hfY9VGViDiSz5i5MmnzXxbKHxdn8Rs+vyGgPJSdGK66XFIgvN15Z19RM7FndBOd/Fx0fELM69w6D8p0s=
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
