---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgCyFHRZ3Z6lLxZmgiNWIByF5BoD26yBNBL9kED65pBoAyE+0v4odaXUyLHXD8dtmbGguncYwK/11FJ+1058AB3NbcJ1xjkz505CLmDrS+oDKhFb2r5wVH6kqRKqzKcptmXFjFQG0TBvFLBFhTfL5CoPVwSrI8dPmx34WJmt5+4ZZh4xQzeM+WBLgmkQAaDw8mRAracOvaIJDabf5eP7OdeS63ZNRpd+ejaZlyV8NYGpjH9v/w07C1NoPu+Wodp+TMdQLMlWcVyoQ2KgGUrdIdc8lDKDeoPwbmDspShZIFQbauvqAoLKZc5gGpyb0ClwBjcZbOtvhecA81oDnY881CMizeqnRQ85ur+nteh5OGDrwtRn/KOBRwZN289YJxUuX+WrvIHV48AKgGDfGntzfm5JgWy6NGK9mufGmqRdFDdbvu8olBEDDadaDq5kiWvD4YLsQsq5vv8AqH7clVlsV8MHg4A/SiE9WGLZ9YvOMDol3LigzJpGObLPUMVMtsWQqnDANyTPoiCsQ8KP93iRRzs7Uw3byrR6ZTsv0rd3bgCBi2082YnmSXJnnhYBmfI5jtv4tiWwWnUuvkqzb4tjqHr9/5YYtby9I1vH4fG7kPECaeX6urgN6GH2rCpSezXVVK54Uxd88Iy00tXf2BZwJusRu/tKgbxZ1ClvPYnDJjNk02bN4VJCOg0VIpTYadh7LApJti46xZGvchGCoExXMGll3FZKhd3MkTQA68cyNeMf6bT2K9KHadUSV1RG1kCA2axMeBQqXFim81Ey4TAkLYaNgBiDtlyfYRcg31raHiihezhx+txmOWgE4MDH4YpwYljozuWDvUQZNy2+p5zfQgsKrPNq0u0=
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
