---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    values.yaml: AgBqh0hBxHqhSjfh1AS2nn4vHaYfUW3ImBPe8vgu1Ufi9LSzjyC531G69+k4gEqCCdHailFhBpHaLM2cS3092mZKbLAjUelw/3YaYjuGII+wfBmlhCoYPew2Hr4wv1wEbbYRAia5AIxP6nAPVptDa3HrVL8+ZbUEQ+2RIRicWlLOuxBbXHcYrpJF8g2OaeOfWI1EnKh9IGsCBwJAUIdkkrKq1a+gs3E0GhLokfMmBWSxXgEv64ZLc6Y1Q5oa+OPJ2v2LKE+79C12gUxE3VXZIRZ9AKx+te+eyjxC9fFQIvtdheqf0xM/zXbNqrwpjkXoHuClIgT39Yx7yzvmx/7nQElggWCM+gckS0HB7stpPcOlmMCxUqloOy1fIolOZF9wGKDd/NHrt0hAp0QoYAQMd+EVzpcrm73Ife9KCIR6KVB8g+VUw3PxtG8ikHLM+bJ6RcxeOaL8u0IjSn8QxIvqx6Ygbp+siymBRq/63FZ0yPEdftDvubK6/9jCjT1NL2r1eCthVlzIUWpIQ4n6z2CmuGlHfJtkmxllyfrliCSNvRwkELdJ6Ra0ZZyusZxJmcrYJPJBPtbyWlBYbyLZKgMAXf9b7f2dj1pZPMVmQYYwu06u8jJjY41wLmzBCBK8EbDYSU0Z7RtLpnwDoNa31yoMDugYd9jV5JMLJ5hUT3PUd3bXZASBKqa7nYnMOHgqWvqamZZr1DrJBAbvO81MFHQYZFO7J9eOBOWWoZqldAUU5IpH11ld+SUYGR+xE7YGtYmyvsRRLeZF94b7iFjllN/Bo3c9nSk08nwPHLGylbG8MZiZ41vCR1rOMKE1eyq6X2JArdm5w/zw6KlhnK6rSR2GiueTFLm8HLw=
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
