apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-operator
  namespace: arc-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: actions-runner-controller
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
