apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sync-stack-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
  volumeMode: Filesystem
