apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
spec:
  interval: 24h
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.x
      sourceRef:
        kind: HelmRepository
        name: home-assistant
      interval: 24h
  valuesFrom: []
