apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pihole
spec:
  interval: 24h
  url: https://mojo2600.github.io/pihole-kubernetes
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: 2.35.x
      sourceRef:
        kind: HelmRepository
        name: pihole
      interval: 24h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom: []
