adminPassword: ENC[AES256_GCM,data:YINrQibr,iv:6WIiBffztQko/KEKD+uAPSqJSeRd8PWPIAcTiXSvmwI=,tag:5JtKIozG9Wo3g7TwprNSPA==,type:str]
sops:
    age:
        - recipient: age1yjhhcgfpsux6tjql3x75hn49e9yyjph4q5ltx67gt6lhryurd9sqgjsam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRmFOalBpU2l5RVorK0x4
            YVp5NXdFK0x0T3lTV0J5ajhKU3lYdWFvV0NVClBnQVBGWTB1RTR2cUFxVDRYQVd2
            STBGRC9WTzFFc1lJSjI1a2xZY2UzMTQKLS0tIDJnSUMvak85TWVWNHlMakZidVFN
            V1NmZExSVXRPdEw0bHBzbFdtRHQyRWcKwd2x1l67IT8AkqIGLP+cyihj1BZ5ETWb
            9GQeMIL8cJbIW1WYWn5EsgJdT0zirgPQMGIxsgrKcKSnS96Jbd6hiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T22:22:04Z"
    mac: ENC[AES256_GCM,data:AMJPNBXCrZTaBZy2k1KzEbPpqaniVk+O4zALZHlnfFZQ+acn0XChVlQi95ZDib8qpy3BbW2OEf9PqR3z6G/cR0/o9s6iBkb12ItG2ckb+V/OuClCt/SUJ3opBmyHsWVhER9VfOhCZquFWUGyLef4P4ps1BVQKKtE98BVPbvYFxc=,iv:Nv/tJF/+56HM/AXxveUMHvCSPRI9TQ87iUKhhjX+StA=,tag:QCBVUrvtZWHXYxh3JL8CTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
