apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palworld-server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: palworld-svc
  replicas: 1
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
      - name: palworld-server
        image: thijsvanloef/palworld-server-docker:v2.3.0@sha256:bafcf4a2ab5026395f2ef4ff1f3949a43db8d408698e7b226c2af51a192f6288
        ports:
        - name: server
          containerPort: 8211
          protocol: UDP
        - name: query
          containerPort: 27015
          protocol: UDP
        envFrom: []
        env: []
        volumeMounts: []
        startupProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          failureThreshold: 120
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          periodSeconds: 20
      volumes: []
