apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palworld-server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: palworld-svc
  replicas: 1
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
      - name: palworld-server
        image: thijsvanloef/palworld-server-docker:v2.3.1@sha256:e2318f3858f4050640564b66cdac2b08fda5600d5c70f394b3679761f8a70f96
        ports:
        - name: server
          containerPort: 8211
          protocol: UDP
        - name: query
          containerPort: 27015
          protocol: UDP
        envFrom: []
        volumeMounts:
        - name: palworld-pvc
          mountPath: /palworld
        startupProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          failureThreshold: 120
          periodSeconds: 5
        readinessProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["sh", "-c", "pgrep PalServer-Linux >/dev/null"]
          periodSeconds: 20
      tolerations:
      - key: storage
        operator: Exists
  volumeClaimTemplates:
  - metadata:
      name: palworld-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 12Gi
