apiVersion: v1
kind: Service
metadata:
  labels:
    app: palworld-server
  name: palworld-svc
spec:
  ports:
    - name: server
      port: 8211
      protocol: UDP
      targetPort: server
    - name: query
      port: 27015
      protocol: UDP
      targetPort: query
  selector:
    app: palworld-server
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: palworld-ingress
spec:
  entryPoints:
  - pals
  routes:
  - services:
    - name: palworld-svc
      port: 8211
      nativeLB: true
