apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: 1.19.x
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    csi:
      pluginTolerations:
      - key: storage
        operator: Exists
      provisionerTolerations:
      - key: storage
        operator: Exists
