apiVersion: v1
kind: Service
metadata:
  name: syncthing-svc
  annotations:
    tailscale.com/tags: "tag:k8s,tag:sync"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: syncthing
  ports:
  - name: tcp
    port: 22000
    targetPort: 22000
