apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stack-pvc
  namespace: media-stack
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ceph-fs
