apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: custom-resources
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./custom-resources/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
