apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./storage/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: rook-ceph-mds-ceph-filesystem-b
      namespace: rook-ceph
  decryption:
    provider: sops
    secretRef:
      name: sops-age
