apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomizations/storage/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - kind: Deployment
      namespace: rook-ceph
      labelSelector:
        app: rook-ceph-rgw
