apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
spec:
  interval: 24h
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.18.x
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 24h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
