apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 12h
  chart:
    spec:
      chart: metallb
      version: 0.15.x
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
