apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.92.x
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 24h
  valuesFrom: []
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
