apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: '0 * * * 1'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: renovate
            image: renovate/renovate:42.92.11@sha256:de9d73d637da5a170d0b43c122d259a5e3baac6a7f7c7b46a89e0b9e9d9938c2
            envFrom: []
            volumeMounts: []
          volumes: []
