apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: '0 0-7 * * *'
  timeZone: America/New_York
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: renovate
            image: renovate/renovate:43.16.0@sha256:29473043843bc89005038c68206e08726efd9ea09b94e88f4b34bd153ab8cf3b
            envFrom: []
            volumeMounts: []
          volumes: []
