apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: '0 0-7 * * *'
  timeZone: America/New_York
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: renovate
            image: renovate/renovate:43.19.0@sha256:d24228ef1500fbc06832a76383e1815402cad86aec180a9a76433634a7e3961f
            envFrom: []
            volumeMounts: []
          volumes: []
