apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  schedule: '0 * * * 1'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 180
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: renovate
            image: renovate/renovate:42.84.2@sha256:8f818dc7f121a48a4d49412516588b8c4c900697455174983328e796f24971ab
            envFrom: []
            volumeMounts: []
          volumes: []
