apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.x
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      interval: 24h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom: []
