---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns
  namespace: ingress
spec:
  encryptedData:
    api-token: AgAQYhNeX+XptTrozwoGyEkLGoOqDAhpyULQ5qEq30RQTGlCrVPSySFa9kRu6EWv2556WcziJUxuXq5b5rbZ0M+Nz8JWdh1JkgWeMfjTgGJQC9lScExqdi4fYqP/ud2rVsAYMhSdtL2yphxNr7Rrfte6lV1AQOgLM25SnoXTnkw2c/WWcvC/e1AkjSvyJa7GUTtDLHPo+Caj2ziQLwcl8arM24N9XMDpAadOfQOCCs2ocCJe/GHhhif1fJgLtrMEgL2dMWAW/Q01TfVHOp5fsWHid7X1ViDa1Vvxc9fUczpL9vPpdxpyH98doxdkwHV/DZySaoV+irPvWPRe8v8+74oso8mto+bERU5AWKRbZnwwDKSIBO5rMe/Dkx7JWCO3KZmIrwe6UabLK2rvc6D5FQ6Pc/Byl7qFoLshUryaWPSb+ARFlPvWePpRXRxidIrvt17mMSgj6EBPg65h8vZW6q+98OzbZyHOOBanxU+uQhq/nWD78ii0MVHr596yqtWAcqKVQFDWT7G27nCaVPrdxibvs9u2QRcTAArZv1cuQJbbKzXriu/5CYz2LVDBQ+3BJL3Hhjh3+HZuyhjX0H1AQcXYW7vBHku2cWQ2IWcbVX5YV2KzmMm4Fh911TDHtf8iuGhC7A+1T58MDPY0heDZMvvrVSdh8S4K+1/tC4ZNHEQails/ze9kUUBu0fduieLUh/eABAymbMeBP2OZ2OpshgzuvFichWVyf3zrJTUiPXOdsrYlEOt6d+Xp
  template:
    metadata:
      name: cloudflare-dns
      namespace: ingress
