apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bazarr
    security: lscr
    storage: media-stack
  name: bazarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - image: lscr.io/linuxserver/bazarr:1.5.5@sha256:f01f718d73be5b468da1ba03e6740c5584769df9d3fedef9f4a3c7eaf90c243f
        name: bazarr
        ports:
        - name: http
          containerPort: 6767
        volumeMounts:
        - name: configdir
          mountPath: /config
        - name: datadir
          mountPath: /data
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: bazarr-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
