apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
    security: lscr
  name: prowlarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - image: lscr.io/linuxserver/prowlarr:2.3.2-nightly@sha256:96443e2fb4b58387bf49057b4b24f0d6c1ac53b214610e982556eb57d94f680c
        name: prowlarr
        ports:
        - name: http
          containerPort: 9696
        volumeMounts:
        - name: configdir
          mountPath: /config
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: prowlarr-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
