apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - image: lscr.io/linuxserver/sonarr:4.0.15-develop@sha256:13250d2a2a25c29701fffaff09480be23e07235753edfc7a74b23d65d66a48b8
        name: sonarr
        ports:
        - name: http
          containerPort: 8989
        envFrom:
        - configMapRef:
            name: linux-server-io-env
        volumeMounts:
        - name: configdir
          mountPath: /config
        - name: datadir
          mountPath: /data
      volumes:
      - name: configdir
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: datadir
        persistentVolumeClaim:
          claimName: media-stack-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
