apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-replicated
spec:
  failureDomain: osd
  replicated:
    size: 3
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: rbd-erasurecoded
spec:
  failureDomain: osd
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: nfs
spec:
  failureDomain: host
  name: .nfs
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-block
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: rook-ceph.rbd.csi.ceph.com # csi-provisioner-name
parameters:
  # rook-ceph cluster namespace
  clusterID: rook-ceph
  dataPool: rbd-erasurecoded
  pool: rbd-replicated
  # RBD image format. Defaults to "2".
  imageFormat: "2"
  imageFeatures: layering
  # The secrets contain Ceph admin credentials. These are generated automatically by the operator in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/controller-publish-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-publish-secret-namespace: rook-ceph # namespace:cluster
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph # namespace:cluster
reclaimPolicy: Delete
