apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-post
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./jobs/crds-post/testing
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds
