apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lb-address-pools
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomizations/lb-address-pools/testing/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: networking
