apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infra/networking/testing/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: storage
  decryption:
    provider: sops
    secretRef:
      name: sops-age
