apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomizations/storage/testing/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: core
  healthChecks:
    - kind: Deployment
      # switch to using selectors?
      name: rook-ceph-mds-ceph-filesystem-b
      namespace: rook-ceph
