apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: palworld-server
  name: palworld-pvc
  namespace: palworld
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
