apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-address-pool
spec:
  addresses:
  - 192.168.192.10-192.168.192.12
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-advertisement
spec:
  ipAddressPools:
  - metallb-address-pool
