apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 12h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 80.5.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: Secret
      name: grafana-admin
      # ingress:
      #   enabled: true
      #   ingressClassName: nginx
      #   hosts:
      #     - grafana.noodoodle.us
